-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024, SINTEF Digital, TNO
-- Copyright (C) 2026, SINTEF Digital

-- Shared grid dimensions and properties.

INIT

DX
30*10
/
DY
30*1
/
DZ
30*1
/

TOPS
30*0
/

PERMX
30*100
/

PERMY
30*100
/

PERMZ
30*100
/

PORO
30*0.1
/
