-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024 Equinor

DENSITY
--   oil   water   gas     
    795.9  1056.   0.906    /

PVTW
-- ref P   FVFW      Cw      ViscW   VoscobW
   900.0   1.062   4.28E-5   0.22    0.0001  /
