-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024 Equinor


WOPR
 A-2H /

WOPRF
 A-2H /

WGPRF
 A-2H /

WWPR
 A-2H /

WBHP
 A-2H /

WMCTL
 A-2H /

WSTAT
 A-2H /

WBP
 A-2H /

WBP9
 A-2H /

WBP4
 A-2H /

WBP5
 A-2H /

COFR
 A-2H /
/

CGFR
 A-2H /
/

CGFRF
 A-2H /
/

CWFR
 A-2H /
/

BPR
 6  7	6  /
 6  7	7  /
 6  7	8  /
 6  7	9  /
 6  7  11  /
 6  7  12  /
 6  7  13  /
 6  7  14  /
 6  7  15  /
 6  7  16  /
 6  7  17  /
 6  7  18  /
 6  7  19  /
 6  7  21  /
 6  7  22  /
 6  7  23  /
 6  7  24  /
 6  7  25  /
 6  7  32  /
 6  7  33  /
 6  7  35  /
 6  7  36  /
 6  7  37  /
 6  7  38  /
 6  7  39  /
 6  7  40  /
 6  7  41  /
/ 
 
BODEN
 6  7	6  /
 6  7	7  /
 6  7	8  /
 6  7	9  /
 6  7  11  /
 6  7  12  /
 6  7  13  /
 6  7  14  /
 6  7  15  /
 6  7  16  /
 6  7  17  /
 6  7  18  /
 6  7  19  /
 6  7  21  /
 6  7  22  /
 6  7  23  /
 6  7  24  /
 6  7  25  /
 6  7  32  /
 6  7  33  /
 6  7  35  /
 6  7  36  /
 6  7  37  /
 6  7  38  /
 6  7  39  /
 6  7  40  /
 6  7  41  /
/ 

BWDEN
 6  7	6  /
 6  7	7  /
 6  7	8  /
 6  7	9  /
 6  7  11  /
 6  7  12  /
 6  7  13  /
 6  7  14  /
 6  7  15  /
 6  7  16  /
 6  7  17  /
 6  7  18  /
 6  7  19  /
 6  7  21  /
 6  7  22  /
 6  7  23  /
 6  7  24  /
 6  7  25  /
 6  7  32  /
 6  7  33  /
 6  7  35  /
 6  7  36  /
 6  7  37  /
 6  7  38  /
 6  7  39  /
 6  7  40  /
 6  7  41  /
/ 

BGDEN
 6  7	6  /
 6  7	7  /
 6  7	8  /
 6  7	9  /
 6  7  11  /
 6  7  12  /
 6  7  13  /
 6  7  14  /
 6  7  15  /
 6  7  16  /
 6  7  17  /
 6  7  18  /
 6  7  19  /
 6  7  21  /
 6  7  22  /
 6  7  23  /
 6  7  24  /
 6  7  25  /
 6  7  32  /
 6  7  33  /
 6  7  35  /
 6  7  36  /
 6  7  37  /
 6  7  38  /
 6  7  39  /
 6  7  40  /
 6  7  41  /
/ 



