<eclipse>
<message source="eclrun" date="" time="0">
Executing ECLIPSE on pc system with x86_64 architecture named PC-40167
</message>
<message source="eclrun" date="" time="0">
Process ID is 20528
</message>
<message source="eclrun" date="" time="0">
Starting HDF conversion ...
</message>
<message source="eclrun" date="" time="0">
HDF conversion completed successfully.
</message>
<message source="eclrun" date="" time="0">
Simulation has finished.
</message>
<message source="eclrun" date="" time="0">
Executing ECLIPSE on pc system with x86_64 architecture named PC-40167
</message>
<message source="eclrun" date="" time="0">
Process ID is 20528
</message>
<message source="eclrun" date="" time="0">
Starting HDF conversion ...
</message>
<message source="eclrun" date="" time="0">
HDF conversion completed successfully.
</message>
<message date="16/6/1988" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="16/6/1988" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="16/6/1988" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     288004 BYTES                                                        
</message>
<warning date="16/6/1988" time="0.00000000000000">
          200 VALUES NOT DEFINED IN BOX (  1- 10,  1- 10,  1-  3)        
 OF KEYWORD TOPS                                                         
</warning>
<message date="16/6/1988" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="16/6/1988" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<message date="16/6/1988" time="0.00000000000000">
 30 NON-NEIGHBOUR CONNECTIONS PRESENT                                    
</message>
<message date="16/6/1988" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 300                                           
</message>
<message date="16/6/1988" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     931488 BYTES                                                        
</message>
<message date="16/6/1988" time="0.00000000000000">
    62181 CHARACTER VARIABLES USED                                       
</message>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6531.94138 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.01230                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6842.28621 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.07111                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7152.63103 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.12539                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7462.97586 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.17567                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7773.32069 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.22244                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8083.66552 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.26608                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8394.01034 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.30695                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8704.35517 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.34534                              
</warning>
<warning date="16/6/1988" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   9014.70000 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.38150                              
</warning>
<message date="16/6/1988" time="0.00000000000000">
 OPENING WELL PROD     AT TIME      0.00   DAYS                          
 CONTROLLED BY OIL RATE                                                  
</message>
<message date="16/6/1988" time="0.00000000000000">
 DRSDT OR DRSDTR KEYWORDS HAVE NOT BEEN                                  
 ENTERED, SO THE MAXIMUM GAS RE-SOLUTION                                 
 RATE IS DEFAULTED TO INFINITY.                                          
</message>
<message date="16/6/1988" time="0.00000000000000">
 ******************************************                              
 * WELL PROD     HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="17/7/1988" time="31.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
</message>
<message date="14/8/1988" time="59.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
</message>
<message date="14/9/1988" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
</message>
<message date="14/10/1988" time="120.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
</message>
<message date="14/11/1988" time="151.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
</message>
<message date="14/12/1988" time="181.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
</message>
<message date="14/1/1989" time="212.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
</message>
<warning date="14/1/1989" time="212.00000000000000">
 LINEAR EQUATION CONVERGENCE PROBLEMS WERE EXPERIENCED THIS              
 TIME-STEP. IN SOME CASES INCREASING LITMAX                              
 (TUNING KEYWORD) AND/OR NSTACK MAY HELP.                                
</warning>
<message date="14/2/1989" time="243.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
</message>
<warning date="14/2/1989" time="243.00000000000000">
 LINEAR EQUATION CONVERGENCE PROBLEMS WERE EXPERIENCED THIS              
 TIME-STEP. IN SOME CASES INCREASING LITMAX                              
 (TUNING KEYWORD) AND/OR NSTACK MAY HELP.                                
</warning>
<message date="16/3/1989" time="273.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
</message>
<warning date="16/3/1989" time="273.00000000000000">
 LINEAR EQUATION CONVERGENCE PROBLEMS WERE EXPERIENCED THIS              
 TIME-STEP. IN SOME CASES INCREASING LITMAX                              
 (TUNING KEYWORD) AND/OR NSTACK MAY HELP.                                
</warning>
<message date="16/4/1989" time="304.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
</message>
<warning date="16/4/1989" time="304.00000000000000">
 LINEAR EQUATION CONVERGENCE PROBLEMS WERE EXPERIENCED THIS              
 TIME-STEP. IN SOME CASES INCREASING LITMAX                              
 (TUNING KEYWORD) AND/OR NSTACK MAY HELP.                                
</warning>
<message date="16/5/1989" time="334.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
</message>
<warning date="16/5/1989" time="334.00000000000000">
 LINEAR EQUATION CONVERGENCE PROBLEMS WERE EXPERIENCED THIS              
 TIME-STEP. IN SOME CASES INCREASING LITMAX                              
 (TUNING KEYWORD) AND/OR NSTACK MAY HELP.                                
</warning>
<message date="16/6/1989" time="365.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
</message>
</eclipse>
