-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026, SINTEF Digital

INIT

GRIDFILE
0 1 /

DX
20*5 /
DY
20*100 /
DZ
20*5 /
TOPS
1*2000.0 /
PORO
20*0.3 /
PERMX
20*2000 /
PERMY
20*2000 /
PERMZ
20*2000 /
