-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026, SINTEF Digital

RPTRST
BASIC=1
PRESSURE
SGAS
SOIL
SWAT
XMF
YMF
ZMF
DENO
DENG
DENW
/

TSTEP
0.01 0.02 0.1 0.2 1.0 5.0
/
