-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026, SINTEF Digital

ALL

-- Block values at the top and the base of each block; layers 10 and 11 face
-- each other across the region boundary.
BPR
1 1 1 /
1 1 10 /
1 1 11 /
1 1 20 /
/

BGSAT
1 1 1 /
1 1 10 /
1 1 11 /
1 1 20 /
/

BOSAT
1 1 1 /
1 1 10 /
1 1 11 /
1 1 20 /
/

BWSAT
1 1 1 /
1 1 10 /
1 1 11 /
1 1 20 /
/
