-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2023 Equinor


WOPR
/

WBHP
/

WTHP
/

WGOR
/

WWCT
/


WVPR
/

WVIR
/

WGIR
/

WWIR
/

FPR

BOSAT
 1 1 1 /
 1 2 1 /
 1 3 1 /
 1 4 1 /
 1 5 1 /
 1 6 1 /
 1 7 1 /
 1 8 1 /
 1 9 1 /
 1 10 1 /
 1 11 1 /
 1 12 1 /
 1 13 1 /
 1 14 1 /
 1 15 1 /
/

BWSAT
 1 1 1 /
 1 2 1 /
 1 3 1 /
 1 4 1 /
 1 5 1 /
 1 6 1 /
 1 7 1 /
 1 8 1 /
 1 9 1 /
 1 10 1 /
 1 11 1 /
 1 12 1 /
 1 13 1 /
 1 14 1 /
 1 15 1 /
/

BGSAT
 1 1 1 /
 1 2 1 /
 1 3 1 /
 1 4 1 /
 1 5 1 /
 1 6 1 /
 1 7 1 /
 1 8 1 /
 1 9 1 /
 1 10 1 /
 1 11 1 /
 1 12 1 /
 1 13 1 /
 1 14 1 /
 1 15 1 /
/

BKRG
 1 1 1 /
 1 2 1 /
 1 3 1 /
 1 4 1 /
 1 5 1 /
 1 6 1 /
 1 7 1 /
 1 8 1 /
 1 9 1 /
 1 10 1 /
 1 11 1 /
 1 12 1 /
 1 13 1 /
 1 14 1 /
 1 15 1 /
/

BKRW
 1 1 1 /
 1 2 1 /
 1 3 1 /
 1 4 1 /
 1 5 1 /
 1 6 1 /
 1 7 1 /
 1 8 1 /
 1 9 1 /
 1 10 1 /
 1 11 1 /
 1 12 1 /
 1 13 1 /
 1 14 1 /
 1 15 1 /
/
