-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026 Equinor


FPR

FGOR

FOPT

FWPT

WBHP
/

WOPR
/

WOPT
/

WWPR
/

WWPT
/

WWCT
/

WGOR
/

FWGR

WWGR
/


CGOR
 'B-1H' /
 'B-2H' /
 'B-3H' /
/ 

CGFR
 'B-1H' /
 'B-2H' /
 'B-3H' /
/ 

COFR
 'B-1H' /
 'B-2H' /
 'B-3H' /
/ 
