-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026 Equinor


FOPT

FWPT

WBHP
/

WOPR
/


WOPT
/

WWPR
/

WWPT
/

WWCT
/

WGOR
/

WWGR
/

FWGR

WWGR
/

CWCT
 'B-1H' /
 'B-2H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 

CWFR
 'B-1H' /
 'B-2H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 

CGFR
 'B-1H' /
 'B-2H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 

COFR
 'B-1H' /
 'B-2H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/

-- Well performance events: include automatic workovers and exclude deck reopens.
WPWE0
/

WPWE1
/

WPWE2
/

WPWE3
/

WPWE4
/

WPWE5
/

WPWE6
/

WPWE7
/
