-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026 Equinor


FWPR

WWPR
/

WWGR
/

FWGR

WBHP
/

WWGR
/

CWFR
 'B-1H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 

CGFR
 'B-1H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 

COFR
 'B-1H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 
CWGR
 'B-1H' /
 'B-3H' /
 'C-1H' /
 'C-2H' /
/ 
