-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   PROD3  11    19     6     6    OPEN   1*  2.294014E+1   0.21600 1*     0.00000 1*    'Z'  /  38.8799  47.0872   22.9401
   PROD3  11    19     7     7    OPEN   1*  1.308895E+1   0.21600 1*     0.00000 1*    'Z'  /  47.0872  57.0771    13.089
   PROD3  11    19     8     8    OPEN   1*  2.780218E+1   0.21600 1*     0.00000 1*    'Z'  /  57.0771   67.067   27.8022
   PROD3  11    19     9     9    OPEN   1*  3.703671E+1   0.21600 1*     0.00000 1*    'Z'  /   67.067     69.5   37.0367
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
