-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   PROD2  10     4     7     7    OPEN   1*  1.645656E+1   0.21600 1*     0.00000 1*    'Z'  /     50.5  58.5359   16.4566
   PROD2  10     4     8     8    OPEN   1*  1.761616E+1   0.21600 1*     0.00000 1*    'Z'  /  58.5359   68.531   17.6162
   PROD2  10     4     9     9    OPEN   1*  8.073011E+1   0.21600 1*     0.00000 1*    'Z'  /   68.531  78.5261   80.7301
   PROD2  10     4    10    10    OPEN   1*  1.019552E+1   0.21600 1*     0.00000 1*    'Z'  /  78.5261  86.8645   10.1955
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
