-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the multi-segment well specification keywords for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
-- ---------------------------------------------------------------------------------------------------------------------------------
--       INJE1 - WELL SEGMENT AND COMPLETION SEGMENT SPECIFICATION DATA                                                     
-- ---------------------------------------------------------------------------------------------------------------------------------
COMPSEGS
-- Name
   INJ1 /
-- I     J      K      Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   2     13     8      1             62.61402         70.89825        /
   2     13     9      1             70.89825         80.88773        /
   2     13     10     1             80.88773         90.87703        /
   2     13     11     1             90.87703         99.94257        /
/   
ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
