-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
    INJ1     2    13     8     8  OPEN   1*  1.703110E+1  0.21600    1*  0.00000    1*  'Z'  /   62.614  70.8983   17.0311
    INJ1     2    13     9     9  OPEN   1*  4.569053E+1  0.21600    1*  0.00000    1*  'Z'  /  70.8983  80.8877   45.6905
    INJ1     2    13    10    10  OPEN   1*  2.558139E+1  0.21600    1*  0.00000    1*  'Z'  /  80.8877   90.877   25.5814
    INJ1     2    13    11    11  OPEN   1*  3.082158E+1  0.21600    1*  0.00000    1*  'Z'  /   90.877  99.9426   30.8216
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
