-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   PROD1   6     3     7     7    OPEN   1*  5.974150E+0   0.21600 1*     0.00000 1*    'Z'  /  54.1443  63.9786   5.97415
   PROD1   6     3     8     8    OPEN   1*  9.831486E+0   0.21600 1*     0.00000 1*    'Z'  /  63.9786  74.2244   9.83149
   PROD1   6     3     9     9    OPEN   1*  1.885740E+2   0.21600 1*     0.00000 1*    'Z'  /  74.2244    84.47   188.574
   PROD1   6     3    10    10    OPEN   1*  4.684912E+1   0.21600 1*     0.00000 1*    'Z'  /    84.47       94   46.8491
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
