-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   INJ1    2    13     1     1    OPEN   1*  1.172656E+2   0.21600 1*     0.00000 1*    'Z'  /        0  8.46488   117.266
   INJ1    2    13     2     2    OPEN   1*  1.330772E+0   0.21600 1*     0.00000 1*    'Z'  /  8.46488  18.4542   1.33077
   INJ1    2    13     3     3    OPEN   1*  3.339084E+1   0.21600 1*     0.00000 1*    'Z'  /  18.4542  24.7358   33.3908  
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
