-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   PROD1   6     3     7     7    OPEN   1*  5.974150E+0   0.21600 1*     0.00000 1*    'Z'  /  54.1443  63.9786   5.97415
   PROD1   6     3     8     8    OPEN   1*  9.831486E+0   0.21600 1*     0.00000 1*    'Z'  /  63.9786  74.2244   9.83149
   PROD1   6     3     9     9    OPEN   1*  1.885740E+2   0.21600 1*     0.00000 1*    'Z'  /  74.2244    84.47   188.574
   PROD1   6     3    10    10    OPEN   1*  4.684912E+1   0.21600 1*     0.00000 1*    'Z'  /    84.47       94   46.8491
                                                                                       
   PROD2  10     4     7     7    OPEN   1*  1.645656E+1   0.21600 1*     0.00000 1*    'Z'  /     50.5  58.5359   16.4566
   PROD2  10     4     8     8    OPEN   1*  1.761616E+1   0.21600 1*     0.00000 1*    'Z'  /  58.5359   68.531   17.6162
   PROD2  10     4     9     9    OPEN   1*  8.073011E+1   0.21600 1*     0.00000 1*    'Z'  /   68.531  78.5261   80.7301
   PROD2  10     4    10    10    OPEN   1*  1.019552E+1   0.21600 1*     0.00000 1*    'Z'  /  78.5261  86.8645   10.1955
                                                                                       
   PROD3  11    19     6     6    OPEN   1*  2.294014E+1   0.21600 1*     0.00000 1*    'Z'  /  38.8799  47.0872   22.9401
   PROD3  11    19     7     7    OPEN   1*  1.308895E+1   0.21600 1*     0.00000 1*    'Z'  /  47.0872  57.0771    13.089
   PROD3  11    19     8     8    OPEN   1*  2.780218E+1   0.21600 1*     0.00000 1*    'Z'  /  57.0771   67.067   27.8022
   PROD3  11    19     9     9    OPEN   1*  3.703671E+1   0.21600 1*     0.00000 1*    'Z'  /   67.067     69.5   37.0367
                                                                                       
   PROD4  11     6     1     1    OPEN   1*  2.985345E+1   0.21600 1*     0.00000 1*    'Z'  /        0   8.3925   29.8535
   PROD4  11     6     2     2    OPEN   1*  6.594767E-1   0.21600 1*     0.00000 1*    'Z'  /   8.3925  18.4021  0.659477
   PROD4  11     6     3     3    OPEN   1*  9.115936E+0   0.21600 1*     0.00000 1*    'Z'  /  18.4021  28.4119   9.11594
   PROD4  11     6     4     4    OPEN   1*  4.141221E+1   0.21600 1*     0.00000 1*    'Z'  /  28.4119  37.2758   41.4122
                                                                                       
   INJ1    2    13     1     1    OPEN   1*  1.172656E+2   0.21600 1*     0.00000 1*    'Z'  /        0  8.46488   117.266
   INJ1    2    13     2     2    OPEN   1*  1.330772E+0   0.21600 1*     0.00000 1*    'Z'  /  8.46488  18.4542   1.33077
   INJ1    2    13     3     3    OPEN   1*  3.339084E+1   0.21600 1*     0.00000 1*    'Z'  /  18.4542  24.7358   33.3908  
   
   INJ2   12    20     9     9    OPEN   1*  1.308560E+2   0.21600 1*     0.00000 1*    'Z'  /  69.1349  78.5404   130.856
   INJ2   12    20    10    10    OPEN   1*  1.940490E+1   0.21600 1*     0.00000 1*    'Z'  /  78.5404  88.5324   19.4049
   INJ2   12    20    11    11    OPEN   1*  6.918248E+1   0.21600 1*     0.00000 1*    'Z'  /  88.5324  97.5105   69.1825
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
