-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   INJ2   12    20     9     9    OPEN   1*  1.308560E+2   0.21600 1*     0.00000 1*    'Z'  /  69.1349  78.5404   130.856
   INJ2   12    20    10    10    OPEN   1*  1.940490E+1   0.21600 1*     0.00000 1*    'Z'  /  78.5404  88.5324   19.4049
   INJ2   12    20    11    11    OPEN   1*  6.918248E+1   0.21600 1*     0.00000 1*    'Z'  /  88.5324  97.5105   69.1825
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
