-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/
--
-- Copyright (C) 2018-2022 Equinor
--
-- This file contains the well specification keywords generate via OPMRUN(WELSPEC) option for MODEL02.
--
--       SWITCH OFF ECHOING OF INPUT FILES
--
NOECHO
--
--  WELL CONNECTION DATA
--
-- WELL   LOC.  LOC.  LOC.  LOC.  OPEN  SAT         CONN     WELL  KH       SKIN  D     DIR       MD-IN   MD-OUT    CONN
-- NAME   II    JJ    K1    K2    SHUT  TAB         FACT     DIA   FACT     FACT  FACT  PEN        MDMS     MDMS    FACTOR
COMPDAT
   PROD4  11     6     1     1    OPEN   1*  2.985345E+1   0.21600 1*     0.00000 1*    'Z'  /        0   8.3925   29.8535
   PROD4  11     6     2     2    OPEN   1*  6.594767E-1   0.21600 1*     0.00000 1*    'Z'  /   8.3925  18.4021  0.659477
   PROD4  11     6     3     3    OPEN   1*  9.115936E+0   0.21600 1*     0.00000 1*    'Z'  /  18.4021  28.4119   9.11594
   PROD4  11     6     4     4    OPEN   1*  4.141221E+1   0.21600 1*     0.00000 1*    'Z'  /  28.4119  37.2758   41.4122
/

ECHO
--
-- *********************************************************************************************************************************
-- END OF FILE
-- *********************************************************************************************************************************
