-- Killough's figure 7:
FGOR
-- Killough's figure 8:
FOPR
-- Killough's figure 9:
FGPR
-- Killough's figure 10:
FWPR
-- Killough's figure 11:
BPR
 1 1 1 /
/
-- Killough's figure 12:
BGSAT
 1 13 1 /
/
-- Killough's figure 13:
BWSAT
 10 25 15 /
/
-- Killough's figure 14:
--WWIR
-- 'INJE1' /
-- Killough's figure 15:
--WOPR
-- 'PRODU21' /

-- In order to compare Eclipse with Flow:
WBHP
/
WGIR
/
--WGIT
--/
WGPR
/
WGPT
/
WOIR
/
--WOIT
--/
WOPR
/
WOPT
/
WWIR
/
--WWIT
--/
WWPR
/
WWPT
/
