-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2025 Equinor

PVTW
  5.0000000e+01   9.8500000e-01   7.0000000e-05   1.3000000e+00   0.0000000e+00 
/
