-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2025 Equinor

SGOF
  0.0000000e+00   0.0000000e+00   1.0000000e+00   0.0000000e+00 
  1.0000000e+00   1.0000000e+00   0.0000000e+00   0.0000000e+00 
/
