-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024 Equinor

MULTFLT
 'CD'  0.10000 / 
 'CD_To'  0.01000 / 
 'CD_B3'  0.10000 / 
 'CD_0'  1.00000 / 
 'C_01'  0.01000 / 
 'C_01_Ti'  0.01000 / 
 'C_08'  0.01000 / 
 'C_08_Ile'  0.10000 / 
 'C_08_S'  0.01000 / 
 'C_08_Ti'  1.00000 / 
 'C_08_S_Ti'  1.00000 / 
 'C_02'  0.01000 / 
 'C_04'  0.05000 / 
 'C_05'  0.10000 / 
 'C_10'  0.01000 / 
 'C_20'  0.50000 / 
 'C_20_LTo'  0.50000 / 
 'C_21'  0.00100 / 
 'C_21_Ti'  0.00100 / 
 'C_23'  0.10000 / 
 'C_24'  0.10000 / 
 'C_25'  0.10000 / 
 'C_26'  0.10000 / 
 'C_26N'  0.00100 / 
 'C_27'  0.05000 / 
 'C_28'  1.00000 / 
 'C_29'  0.10000 / 
 'DI_S'  0.10000 / 
 'm_east'  1.00000 / 
 'm_west'  1.00000 / 
/
