-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2018 Equinor

-- This file is one of the include files for model2

COMPSEGS
-- Name
   INJ1 /
-- I     J      K      Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   2     13     8      1             62.61402         70.89825        /
   2     13     9      1             70.89825         80.88773        /
   2     13     10     1             80.88773         90.87703        /
   2     13     11     1             90.87703         99.94257        /
    /
