
COMPSEGS
-- Name
   INJ1 /
-- I     J      K      Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   2     13     8      1             62.61402         70.89825        /
   2     13     9      1             70.89825         80.88773        /
   2     13     10     1             80.88773         90.87703        /
   2     13     11     1             90.87703         99.94257        /
    /
