WELSEGS
-- Name      Dep 1          Tlen 1      Vol 1     Len&Dep     PresDrop
   PROD3     2588.50986     0.00000     1*        INC         'HF-'    /
-- First Seg     Last Seg     Branch Num     Outlet Seg     Length      Depth Change     Diam        Rough    
-- Main Stem Segments
   2             2            1              1              2.31517     2.31480          0.15200     0.0000100 /
   3             3            1              2              7.31010     7.30893          0.15200     0.0000100 /
   4             4            1              3              9.98989     9.98829          0.15200     0.0000100 /
   5             5            1              4              9.98985     9.98825          0.15200     0.0000100 /
   6             6            1              5              6.24364     6.24264          0.15200     0.0000100 /
   7             7            1              6              6.24365     6.24265          0.15200     0.0000100 /
   8             8            1              7              9.98983     9.98822          0.15200     0.0000100 /
   9             9            1              8              9.98988     9.98828          0.15200     0.0000100 /
   10            10           1              9              7.93418     7.93291          0.15200     0.0000100 /
    /
COMPSEGS
-- Name 
   PROD3 /
-- I      J      K     Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   11     19     6     1             38.87991         47.08721        /
   11     19     7     1             47.08721         57.07705        /
   11     19     8     1             57.07705         67.06696        /
   11     19     9     1             67.06696         69.50000        /
    /
