WELSEGS
-- Name      Dep 1          Tlen 1      Vol 1     Len&Dep     PresDrop
   PROD1     1203.20924     0.00000     1*        INC         'HF-'    /
-- First Seg     Last Seg     Branch Num     Outlet Seg     Length        Depth Change     Diam        Rough  
-- Main Stem Segments
   2             2            1              1              49.36537      3.56589          0.15200     0.00001 /
   3             3            1              2              30.19023      2.18078          0.15200     0.00001 /
   4             4            1              3              51.60245      3.50733          0.15200     0.00001 /
   5             5            1              4              28.86132      1.74377          0.15200     0.00001 /
   6             6            1              5              26.86858      1.47015          0.15200     0.00001 /
   7             7            1              6              76.95933      3.36675          0.15200     0.00001 /
   8             8            1              7              100.40827     1.64935          0.15200     0.00001 /
   9             9            1              8              100.04913     1.24179          0.15200     0.00001 /
   10            10           1              9              100.11563     4.65494          0.15200     0.00001 /
   11            11           1              10             20.87728      0.98829          0.15200     0.00001 /
   12            12           1              11             79.28369      3.20814          0.15200     0.00001 /
   13            13           1              12             61.52252      2.31993          0.15200     0.00001 /
-- Perforation Valve Segments
-- Diam: MSW - Tubing Radius
-- Rough: MSW - Open Hole Roughness Factor
-- Combined Valve for segment #2 with contribution from: 10 ICDs: 0 - 726.104 #1, 10 ICDs: 0 - 726.104 #2
   14            14           2              2              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #3 with contribution from: 10 ICDs: 0 - 726.104 #2
   15            15           3              3              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #4 with contribution from: 10 ICDs: 0 - 726.104 #2, 10 ICDs: 0 - 726.104 #3
   16            16           4              4              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #5 with contribution from: 10 ICDs: 0 - 726.104 #3
   17            17           5              5              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #6 with contribution from: 10 ICDs: 0 - 726.104 #3
   18            18           6              6              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #7 with contribution from: 10 ICDs: 0 - 726.104 #3, 10 ICDs: 0 - 726.104 #4
   19            19           7              7              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #8 with contribution from: 10 ICDs: 0 - 726.104 #4, 10 ICDs: 0 - 726.104 #5, 10 ICDs: 0 - 726.104 #6
   20            20           8              8              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #9 with contribution from: 10 ICDs: 0 - 726.104 #6, 10 ICDs: 0 - 726.104 #7
   21            21           9              9              0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #10 with contribution from: 10 ICDs: 0 - 726.104 #7, 10 ICDs: 0 - 726.104 #8
   22            22           10             10             0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #11 with contribution from: 10 ICDs: 0 - 726.104 #8
   23            23           11             11             0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #12 with contribution from: 10 ICDs: 0 - 726.104 #8, 10 ICDs: 0 - 726.104 #9
   24            24           12             12             0.10000       0                0.15200     0.00001 /
-- Combined Valve for segment #13 with contribution from: 10 ICDs: 0 - 726.104 #9, 10 ICDs: 0 - 726.104 #10
   25            25           13             13             0.10000       0                0.15200     0.00001 /
    /
COMPSEGS
-- Name 
   PROD1 /
-- I     J     K     Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   2     2     1     2             0.00000          0.10000         /
   3     2     1     3             0.00000          0.10000         /
   3     2     2     4             1.12260          1.22260         /
   3     3     2     5             0.00000          0.10000         /
   4     3     2     6             1.33703          1.43703         /
   4     3     3     7             55.14666         55.24666        /
   5     3     3     8             58.86552         58.96552        /
   6     3     3     9             39.13545         39.23545        /
   7     3     3     10            19.76452         19.86452        /
   8     3     3     11            0.32709          0.42709         /
   8     3     4     12            60.12801         60.22801        /
   9     3     4     13            0.00000          0.10000         /
    /
WSEGVALV
-- Well Name     Seg No     Cv          Ac      
-- Combined Valve for segment #2 with contribution from: 10 ICDs: 0 - 726.104 #1, 10 ICDs: 0 - 726.104 #2
   PROD1         14         0.70000     5.589e-5 /
-- Combined Valve for segment #3 with contribution from: 10 ICDs: 0 - 726.104 #2
   PROD1         15         0.70000     1.881e-5 /
-- Combined Valve for segment #4 with contribution from: 10 ICDs: 0 - 726.104 #2, 10 ICDs: 0 - 726.104 #3
   PROD1         16         0.70000     3.215e-5 /
-- Combined Valve for segment #5 with contribution from: 10 ICDs: 0 - 726.104 #3
   PROD1         17         0.70000     1.798e-5 /
-- Combined Valve for segment #6 with contribution from: 10 ICDs: 0 - 726.104 #3
   PROD1         18         0.70000     1.674e-5 /
-- Combined Valve for segment #7 with contribution from: 10 ICDs: 0 - 726.104 #3, 10 ICDs: 0 - 726.104 #4
   PROD1         19         0.70000     4.795e-5 /
-- Combined Valve for segment #8 with contribution from: 10 ICDs: 0 - 726.104 #4, 10 ICDs: 0 - 726.104 #5, 10 ICDs: 0 - 726.104 #6
   PROD1         20         0.70000     6.256e-5 /
-- Combined Valve for segment #9 with contribution from: 10 ICDs: 0 - 726.104 #6, 10 ICDs: 0 - 726.104 #7
   PROD1         21         0.70000     6.233e-5 /
-- Combined Valve for segment #10 with contribution from: 10 ICDs: 0 - 726.104 #7, 10 ICDs: 0 - 726.104 #8
   PROD1         22         0.70000     6.238e-5 /
-- Combined Valve for segment #11 with contribution from: 10 ICDs: 0 - 726.104 #8
   PROD1         23         0.70000     1.301e-5 /
-- Combined Valve for segment #12 with contribution from: 10 ICDs: 0 - 726.104 #8, 10 ICDs: 0 - 726.104 #9
   PROD1         24         0.70000      4.94e-5 /
-- Combined Valve for segment #13 with contribution from: 10 ICDs: 0 - 726.104 #9, 10 ICDs: 0 - 726.104 #10
   PROD1         25         0.70000     6.346e-5 /
    /
