WELSPECS
-- Well   Grp  I  J  RefDepth  Type  DrainRad  GasInEq  AutoShut  XFlow  FluidPVT  HydSDens  FluidInPlReg
   PROD1  TEST   2  2  1*        OIL   0.0       STD      SHUT      YES    0         SEG       0            /
    /
    
COMPDAT
-- Well    I   J   K1   K2   Status   SAT   TR            DIAM      KH   S         Df   DIR
-- ---- Completions for completion type Perforation ----
-- Perforation Completion : MD In: 0 - MD Out: 49.3654 Transmissibility: 4691.86
   PROD1   2   2   1    1    OPEN     1*    4.691865E+3   0.21600   1*   0.00000   1*   'Z' /
-- Perforation Completion : MD In: 49.3654 - MD Out: 79.5556 Transmissibility: 5551.23
   PROD1   3   2   1    1    OPEN     1*    5.551235E+3   0.21600   1*   0.00000   1*   'Z' /
-- Perforation Completion : MD In: 79.5556 - MD Out: 131.158 Transmissibility: 2865.37
   PROD1   3   2   2    2    OPEN     1*    2.865370E+3   0.21600   1*   0.00000   1*   'Z' /
-- Perforation Completion : MD In: 131.158 - MD Out: 160.019 Transmissibility: 736.519
   PROD1   3   3   2    2    OPEN     1*    7.365187E+2   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 160.019 - MD Out: 186.888 Transmissibility: 1343.29
   PROD1   4   3   2    2    OPEN     1*    1.343294E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 186.888 - MD Out: 263.847 Transmissibility: 2085.07
   PROD1   4   3   3    3    OPEN     1*    2.085070E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 263.847 - MD Out: 364.256 Transmissibility: 1894.88
   PROD1   5   3   3    3    OPEN     1*    1.894876E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 364.256 - MD Out: 464.305 Transmissibility: 2942.19
   PROD1   6   3   3    3    OPEN     1*    2.942194E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 464.305 - MD Out: 564.42 Transmissibility: 2632.39
   PROD1   7   3   3    3    OPEN     1*    2.632392E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 564.42 - MD Out: 585.298 Transmissibility: 484.957
   PROD1   8   3   3    3    OPEN     1*    4.849574E+2   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 585.298 - MD Out: 664.581 Transmissibility: 9241.69
   PROD1   8   3   4    4    OPEN     1*    9.241692E+3   0.21600   1*   0.00000   1*   'X' /
-- Perforation Completion : MD In: 664.581 - MD Out: 726.104 Transmissibility: 6876.02
   PROD1   9   3   4    4    OPEN     1*    6.876024E+3   0.21600   1*   0.00000   1*   'X' /
    /
