-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2018 Equinor

-- This is a test case for implementing WSEGVALV keyword

WOPR
 PROD1 / 
 
WGOR
 PROD1 / 

WBHP
 PROD1 / 

WWCT
 PROD1 / 

WOPT
 PROD1 / 

WWPT
 PROD1 / 
