-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024 Equinor

FGPR

FOPR

FPR

TCPU

TIMESTEP

WBHP
/

WOPR
/

WGPR
/

WWPR
/

WLPR
/

WWCT
/

WGOR
/

FGOR
/

WGPRT
/ 

WOPRT
/ 

WWPRT
/ 

WLPRT
/ 

WMCTL
/

WTHP
/
 
WWIR
/

WGIR
/

WWIRT
/

WGIRT
/

BPR
 5 3 1 /
/

RPR
/

GOPR
/

GWIR
/

FGLIR
 
GGLIR
 'LOWER' /
 
WGLIR
 'E-1H' 'E-2H' /

GUGR
/

GGPR
/ 

FUGAS
