-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2019 Equinor


WELSEGS
-- Name     Dep 1          Tlen 1      Vol 1     Len&Dep     PresDrop
   C-2H     2534.61007     0.00000     1*        INC         'HF-'    /
-- First Seg     Last Seg     Branch Num     Outlet Seg     Length       Depth Change     Diam        Rough    
-- Main Stem Segments
   2             2            1              1              6.34150      5.82330          0.15200     0.0000100 /
   3             3            1              2              9.65693      8.86781          0.15200     0.0000100 /
   4             4            1              3              11.38731     10.45678         0.15200     0.0000100 /
   5             5            1              4              10.38738     9.53857          0.15200     0.0000100 /
   6             6            1              5              6.58077      6.04302          0.15200     0.0000100 /
   7             7            1              6              6.57944      6.04180          0.15200     0.0000100 /
   8             8            1              7              6.84335      6.28414          0.15200     0.0000100 /
   9             9            1              8              6.84282      6.28365          0.15200     0.0000100 /
   10            10           1              9              6.94475      6.37725          0.15200     0.0000100 /
   11            11           1              10             15.38039     14.12357         0.15200     0.0000100 /
   12            12           1              11             8.05975      7.40114          0.15200     0.0000100 /
   13            13           1              12             3.64496      3.34711          0.15200     0.0000100 /
   14            14           1              13             13.22470     12.14404         0.15200     0.0000100 /
   15            15           1              14             13.17200     12.09564         0.15200     0.0000100 /
   16            16           1              15             13.11589     12.04411         0.15200     0.0000100 /
   17            17           1              16             10.77646     9.89585          0.15200     0.0000100 /
   18            18           1              17             2.28455      2.09786          0.15200     0.0000100 /
   19            19           1              18             4.16883      3.82817          0.15200     0.0000100 /
   20            20           1              19             21.19119     19.45953         0.15200     0.0000100 /
   21            21           1              20             22.77678     20.91556         0.15200     0.0000100 /
   22            22           1              21             46.27217     42.49101         0.15200     0.0000100 /
   23            23           1              22             27.81882     25.54559         0.15200     0.0000100 /
    /
    
COMPSEGS
-- Name
   C-2H /
-- I      J      K      Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   24     14     19     1             156.14037        176.58296       /
   24     14     20     1             176.58296        197.15798       /
    /
