-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2025 Equinor

BCCON
       1        1        1        1       15        1       14         X- / 
       2       15       15        1       15        1       14         X+ / 
       3        1       15        1        1        1       14         Y- / 
       4        1       15       15       15        1       14         Y+ / 
       5        1       15        1       15        1        1         Z- / 
       6        1       15        1       15       14       14         Z+ / 
/
