-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2025 Equinor

STREQUIL
  0.0000000e+00   0.0000000e+00   0.0000000e+00   0.0000000e+00   1.6700000e-01   0.0000000e+00   1.6700000e-01   0.0000000e+00   2.2000000e-01 /
/
