-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2024 Equinor

TCPU

TIMESTEP

FPR

FOPR

FGOR

FWCT

FWPR

FGPR

WBHP
/

WTHP
/

WOPR
/

WGPR
/

WGOR
/

WWCT
/


RPR
 1  /
 

ROIP
 1 /

RGIP
 1 /


GPR
/

WOPT
/

WWPT
/

WGPT
/

WGIT
/

WWIT
/

WEFFG
/
