-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2022 Equinor

-- This file is one of the include files for model2

-- Summary file for the base case, specific version

COFR
 'EXP1' /
/

COPT
 'EXP1' /
/

COPTL
 'EXP1' /
/

CWFR
 'EXP1' /
/

CGFR
 'EXP1' /
/

FPR

RPR
/

ROIP
/

RGIP
/

RWIP
/

ROFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RGFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

ROFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

ROFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/


RGFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RGFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/


WOPR
 OP_1 OP_2 /
 
WOPT
 OP_1 OP_2  /

WBHP
 OP_1 OP_2 GI_1 WI_1 /

WGOR
 OP_1 OP_2  /

WWCT
 OP_1 OP_2  /
 
WGIR
  GI_1 /

WGIT
  GI_1 /

WWIR
 WI_1 /  
 
WWIT
 WI_1 /  

BFLOGI
4 4 2 /
1 1 3 /
3 2 3 /
8 9 5 /
2 2 2 /
/

BFLOGJ
8 9 6 /
/

BFLOGK
7 7 7 /
/

BFLOOI
7 9 6 /
/

BFLOOJ
5 5 4 /
/

BFLOOK
10 12 2 /
/

BFLOWI
8 12 8 /
/

BFLOWJ
10 9 8 /
/

BFLOWK
10 12 5 /
/

BFLOGI-
2 1 1 /
/

BFLOGJ-
1 2 1 /
/

BFLOGK-
1 1 2 /
/

BFLOOI-
3 1 1 /
/

BFLOOJ-
1 3 1 /
/

BFLOOK-
2 2 4 /
/

BFLOWI-
4 1 1 /
/

BFLOWJ-
1 4 1 /
/

BFLOWK-
2 2 3 /
/
