-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2022 Equinor

-- This file is one of the include files for model2

-- Summary file for the base case, specific version

COFR
 'EXP1' /
/

COPT
 'EXP1' /
/

COPTL
 'EXP1' /
/

CWFR
 'EXP1' /
/

CGFR
 'EXP1' /
/

FPR

RPR
/

ROIP
/

RGIP
/

RWIP
/

ROFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RGFT
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

ROFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

ROFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RWFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/


RGFT+
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/

RGFT-
 1 2 /
 1 3 /
 1 4 /
 2 3 /
 2 4 /
 3 4 /
/


WOPR
 OP_1 OP_2 /
 
WOPT
 OP_1 OP_2  /

WBHP
 OP_1 OP_2 GI_1 WI_1 /

WGOR
 OP_1 OP_2  /

WWCT
 OP_1 OP_2  /
 
WGIR
  GI_1 /

WGIT
  GI_1 /

WWIR
 WI_1 /  
 
WWIT
 WI_1 /  
