<eclipse>
<message date="6/11/2011" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="6/11/2011" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="6/11/2011" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     231972 BYTES                                                        
</message>
<comment date="6/11/2011" time="0.00000000000000">
 NEWTRAN SPECIFIED IN BLOCK-CENTRED GEOMETRY                             
 IS NOT RECOMMENDED. CHECK THE GRID DATA.                                
</comment>
<comment date="6/11/2011" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="6/11/2011" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 96                                            
</message>
<warning date="6/11/2011" time="0.00000000000000">
 NSTACK =     30   WHICH EXCEEDS THE                                     
 LARGEST VALUE OF LITMAX IN THE DECK,  WHICH IS     25  .                
 THE EXCESS MEMORY REQUESTED BY NSTACK WILL NOT BE USED                  
 AND WILL REDUCE PERFORMANCE AND MAY CAUSE MEMORY OVERFLOW.              
 NSTACK WILL BE REDUCED                                                  
 TO THE LARGEST LITMAX VALUE IN THE DECK.                                
 SET OPTIONS(256)=1 TO STOP THIS FROM HAPPENING.                         
</warning>
<message date="6/11/2011" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     914608 BYTES                                                        
</message>
<message date="6/11/2011" time="0.00000000000000">
    62292 CHARACTER VARIABLES USED                                       
</message>
<warning date="6/11/2011" time="0.00000000000000">
 SPURIOUS DATA BEFORE AQUANCON KEYWORD                                   
 /                                                                       
</warning>
<warning date="6/11/2011" time="0.00000000000000">
 A CELL HAS BEEN DETECTED IN AQUANCON                                    
 THAT HAS AN ACTIVE CELL ON ITS                                          
 AQUIFER FACING SIDE. THIS CELL WILL                                     
 NOT BE CONNECTED. A FULL LIST OF                                        
 CELLS CAN BE OBTAINED USING                                             
 OPTIONS(99). IN ORDER TO CONNECT                                        
 THESE CELLS SET ITEM 11 OF AQUANCON.                                    
</warning>
<warning date="6/11/2011" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SWAT             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="6/11/2011" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SGAS             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="6/11/2011" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SOIL             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<message date="6/11/2011" time="0.00000000000000">
 AQUIFER      1 HAS      5 CONNECTIONS IN THE                            
 GLOBAL GRID                                                             
</message>
<message date="6/11/2011" time="0.00000000000000">
 AQUIFER      2 HAS      5 CONNECTIONS IN THE                            
 GLOBAL GRID                                                             
</message>
<comment date="6/11/2011" time="0.00000000000000">
 THE MINIMUM VALUE FOR NCAMAX IN THE AQUDIMS KEYWORD                     
 IN RUNSPEC IS         5                                                 
</comment>
<message date="6/11/2011" time="0.00000000000000">
 OPTIONS(137) HAS BEEN SET TO RESTORE PRE-2009.1                         
 BEHAVIOR FOR VELOCITY CALCULATION                                       
</message>
<warning date="6/11/2011" time="0.00000000000000">
 WELL INJE01   CONNECTS WITH A DEAD BLOCK                                
 (   1   1   5). THIS CONNECTION WILL BE IGNORED.                        
</warning>
<message date="6/11/2011" time="0.00000000000000">
 ****************************************************                    
 * WELL INJE01   IS     SHUT AT TIME      0.00  DAYS  *                  
 ****************************************************                    
</message>
<message date="6/11/2011" time="0.00000000000000">
 OPENING WELL PROD01   AT TIME      0.00   DAYS                          
 CONTROLLED BY BOTTOM HOLE PRESSURE                                      
</message>
<message date="6/11/2011" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="21/11/2011" time="15.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="6/12/2011" time="30.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="21/12/2011" time="45.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="5/1/2012" time="60.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="20/1/2012" time="75.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="4/2/2012" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="19/2/2012" time="105.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="5/3/2012" time="120.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="20/3/2012" time="135.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="4/4/2012" time="150.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="19/4/2012" time="165.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="4/5/2012" time="180.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="19/5/2012" time="195.00000000000000">
 RESTART FILE WRITTEN   REPORT    13                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="3/6/2012" time="210.00000000000000">
 RESTART FILE WRITTEN   REPORT    14                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="18/6/2012" time="225.00000000000000">
 RESTART FILE WRITTEN   REPORT    15                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="3/7/2012" time="240.00000000000000">
 RESTART FILE WRITTEN   REPORT    16                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="18/7/2012" time="255.00000000000000">
 RESTART FILE WRITTEN   REPORT    17                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="2/8/2012" time="270.00000000000000">
 RESTART FILE WRITTEN   REPORT    18                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="17/8/2012" time="285.00000000000000">
 RESTART FILE WRITTEN   REPORT    19                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="1/9/2012" time="300.00000000000000">
 RESTART FILE WRITTEN   REPORT    20                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="16/9/2012" time="315.00000000000000">
 RESTART FILE WRITTEN   REPORT    21                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="1/10/2012" time="330.00000000000000">
 RESTART FILE WRITTEN   REPORT    22                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="16/10/2012" time="345.00000000000000">
 RESTART FILE WRITTEN   REPORT    23                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="31/10/2012" time="360.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="15/11/2012" time="375.00000000000000">
 RESTART FILE WRITTEN   REPORT    25                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="30/11/2012" time="390.00000000000000">
 RESTART FILE WRITTEN   REPORT    26                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="15/12/2012" time="405.00000000000000">
 RESTART FILE WRITTEN   REPORT    27                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="30/12/2012" time="420.00000000000000">
 RESTART FILE WRITTEN   REPORT    28                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="14/1/2013" time="435.00000000000000">
 RESTART FILE WRITTEN   REPORT    29                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="29/1/2013" time="450.00000000000000">
 RESTART FILE WRITTEN   REPORT    30                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="13/2/2013" time="465.00000000000000">
 RESTART FILE WRITTEN   REPORT    31                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="28/2/2013" time="480.00000000000000">
 RESTART FILE WRITTEN   REPORT    32                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="15/3/2013" time="495.00000000000000">
 RESTART FILE WRITTEN   REPORT    33                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="30/3/2013" time="510.00000000000000">
 RESTART FILE WRITTEN   REPORT    34                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="14/4/2013" time="525.00000000000000">
 RESTART FILE WRITTEN   REPORT    35                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="29/4/2013" time="540.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="14/5/2013" time="555.00000000000000">
 RESTART FILE WRITTEN   REPORT    37                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="29/5/2013" time="570.00000000000000">
 RESTART FILE WRITTEN   REPORT    38                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="13/6/2013" time="585.00000000000000">
 RESTART FILE WRITTEN   REPORT    39                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="28/6/2013" time="600.00000000000000">
 RESTART FILE WRITTEN   REPORT    40                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="13/7/2013" time="615.00000000000000">
 RESTART FILE WRITTEN   REPORT    41                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="28/7/2013" time="630.00000000000000">
 RESTART FILE WRITTEN   REPORT    42                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="12/8/2013" time="645.00000000000000">
 RESTART FILE WRITTEN   REPORT    43                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="27/8/2013" time="660.00000000000000">
 RESTART FILE WRITTEN   REPORT    44                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="11/9/2013" time="675.00000000000000">
 RESTART FILE WRITTEN   REPORT    45                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="26/9/2013" time="690.00000000000000">
 RESTART FILE WRITTEN   REPORT    46                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="11/10/2013" time="705.00000000000000">
 RESTART FILE WRITTEN   REPORT    47                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="26/10/2013" time="720.00000000000000">
 RESTART FILE WRITTEN   REPORT    48                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="10/11/2013" time="735.00000000000000">
 RESTART FILE WRITTEN   REPORT    49                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="25/11/2013" time="750.00000000000000">
 RESTART FILE WRITTEN   REPORT    50                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="10/12/2013" time="765.00000000000000">
 RESTART FILE WRITTEN   REPORT    51                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="25/12/2013" time="780.00000000000000">
 RESTART FILE WRITTEN   REPORT    52                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="9/1/2014" time="795.00000000000000">
 RESTART FILE WRITTEN   REPORT    53                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="24/1/2014" time="810.00000000000000">
 RESTART FILE WRITTEN   REPORT    54                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="8/2/2014" time="825.00000000000000">
 RESTART FILE WRITTEN   REPORT    55                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="23/2/2014" time="840.00000000000000">
 RESTART FILE WRITTEN   REPORT    56                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="10/3/2014" time="855.00000000000000">
 RESTART FILE WRITTEN   REPORT    57                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="25/3/2014" time="870.00000000000000">
 RESTART FILE WRITTEN   REPORT    58                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="9/4/2014" time="885.00000000000000">
 RESTART FILE WRITTEN   REPORT    59                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
<message date="24/4/2014" time="900.00000000000000">
 RESTART FILE WRITTEN   REPORT    60                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
                  VELOCITIES                                             
</message>
</eclipse>
