-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2026 Equinor

-- Timestep event indicators and rates/status used to interpret them.

WPWE0
/

WPWE1
/

WPWE2
/

WPWE3
/

WPWE4
/

WPWE5
/

WPWE6
/

WPWE7
/

WOPR
/
WWIR
/
WSTAT
/
WWCT
/
WGOR
/
